spring.application.name=Mann_Ki_Avaj
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/mann_ki_aavaj?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.main.banner-mode=off
logging.level.root=INFO

jwt.secret=1234567890123456789012345678901234567890123456789012345678901234
jwt.expiration=86400000


# ===============================
# EMAIL CONFIGURATION
# ===============================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ghubeniraj90@gmail.com
spring.mail.password=gdgicxoilxdwsldt

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



