package db.migration;

import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class V3__create_community_audio_attachments extends BaseJavaMigration {
    @Override
    public void migrate(Context context) throws Exception {
        Connection connection = context.getConnection();
        if (tableExists(connection, "community_audio_attachments")
                || !tableExists(connection, "posts") || !tableExists(connection, "music_tracks")) return;
        String identity = connection.getMetaData().getDatabaseProductName().toLowerCase().contains("mysql")
                ? "BIGINT AUTO_INCREMENT" : "BIGINT GENERATED BY DEFAULT AS IDENTITY";
        try (Statement statement = connection.createStatement()) {
            statement.execute("CREATE TABLE community_audio_attachments (" +
                    "id " + identity + " PRIMARY KEY," +
                    "post_id BIGINT NOT NULL, audio_kind VARCHAR(30) NOT NULL," +
                    "music_track_id BIGINT NULL, duration_seconds INTEGER NULL," +
                    "created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NULL," +
                    "CONSTRAINT uk_community_audio_post UNIQUE (post_id)," +
                    "CONSTRAINT uk_community_audio_music_track UNIQUE (music_track_id)," +
                    "CONSTRAINT fk_community_audio_post FOREIGN KEY (post_id) REFERENCES posts(id)," +
                    "CONSTRAINT fk_community_audio_music_track FOREIGN KEY (music_track_id) REFERENCES music_tracks(id))");
            statement.execute("CREATE INDEX idx_community_audio_post ON community_audio_attachments(post_id)");
            statement.execute("CREATE INDEX idx_community_audio_music_track ON community_audio_attachments(music_track_id)");
        }
    }

    private static boolean tableExists(Connection connection, String name) throws SQLException {
        try (ResultSet rows = connection.getMetaData().getTables(connection.getCatalog(), null, null, new String[]{"TABLE"})) {
            while (rows.next()) if (name.equalsIgnoreCase(rows.getString("TABLE_NAME"))) return true;
        }
        return false;
    }
}
